//Valid login
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "lghiggino",
    "password": "ghiggino"
}

###
//wrong username or password

post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "mluukkai"
}

